/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectodesarrollo;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author kevin
 */
public class Bienvenida extends javax.swing.JFrame implements Runnable {
        
    //VARIABLES UTILIZADAS EN EL RELOJ
    int hora, segundo, minuto;
    int dia, mes, año;
    String horastr, añostr;
    
    Manejador manejador;
    /**
     * Creates new form Bienvenidos
     */
    public Bienvenida() {
        
        initComponents();
        EdicionDeCodigoGenerado();
        setLocationRelativeTo(this);
        this.setVisible(true);
        Thread t = new Thread(this); 
        t.start();

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Texto1 = new javax.swing.JLabel();
        barranegra = new javax.swing.JLabel();
        PanelImagenes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JBIniciosecc = new javax.swing.JButton();
        FondoLogin = new javax.swing.JLabel();
        PanelSuperior = new javax.swing.JPanel();
        TituloDescanso = new javax.swing.JLabel();
        TituloHotel = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestión hotelera - Hotel El descanso");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        PanelFondo.setBackground(new java.awt.Color(204, 204, 255));
        PanelFondo.setOpaque(false);
        PanelFondo.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 26)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("en nuestras instalaciones.");
        PanelFondo.add(jLabel4);
        jLabel4.setBounds(50, 380, 370, 50);

        Texto1.setFont(new java.awt.Font("Dialog", 0, 26)); // NOI18N
        Texto1.setForeground(new java.awt.Color(255, 255, 255));
        Texto1.setText("Disfruta tus vacaciones hospedandote");
        PanelFondo.add(Texto1);
        Texto1.setBounds(50, 350, 500, 50);

        barranegra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barranegra.png"))); // NOI18N
        PanelFondo.add(barranegra);
        barranegra.setBounds(0, 40, 510, 420);

        PanelImagenes.setBackground(new java.awt.Color(25, 25, 25));
        PanelImagenes.setForeground(new java.awt.Color(40, 40, 40));
        PanelImagenes.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PresentacionImagenes.gif"))); // NOI18N
        PanelImagenes.add(jLabel1);
        jLabel1.setBounds(0, 10, 290, 160);

        jLabel2.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<html>Contamos con gran variedad en entretenimiento tales como; acceso a piscinas, gimnasio, restaurante e incluso contamos con zonas verdes para la recreación y entretenimiento familiar.<html>");
        PanelImagenes.add(jLabel2);
        jLabel2.setBounds(15, 180, 273, 100);

        PanelFondo.add(PanelImagenes);
        PanelImagenes.setBounds(510, 130, 290, 319);

        JBIniciosecc.setBackground(new java.awt.Color(255, 204, 51));
        JBIniciosecc.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        JBIniciosecc.setForeground(new java.awt.Color(0, 0, 0));
        JBIniciosecc.setText("Iniciar Sesión");
        JBIniciosecc.setToolTipText("");
        PanelFondo.add(JBIniciosecc);
        JBIniciosecc.setBounds(507, 60, 300, 60);
        JBIniciosecc.setBorder(null);

        FondoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo3.jpg"))); // NOI18N
        PanelFondo.add(FondoLogin);
        FondoLogin.setBounds(0, 0, 810, 500);

        getContentPane().add(PanelFondo);
        PanelFondo.setBounds(0, 100, 800, 500);

        PanelSuperior.setBackground(new java.awt.Color(34, 34, 34));
        PanelSuperior.setLayout(null);

        TituloDescanso.setFont(new java.awt.Font("Impact", 0, 42)); // NOI18N
        TituloDescanso.setForeground(new java.awt.Color(255, 255, 255));
        TituloDescanso.setText("EL DESCANSO");
        PanelSuperior.add(TituloDescanso);
        TituloDescanso.setBounds(30, 20, 390, 40);

        TituloHotel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TituloHotel.setForeground(new java.awt.Color(255, 204, 51));
        TituloHotel.setText("HOTEL");
        PanelSuperior.add(TituloHotel);
        TituloHotel.setBounds(160, 50, 90, 40);

        time.setFont(new java.awt.Font("Impact", 0, 35)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        PanelSuperior.add(time);
        time.setBounds(643, 20, 220, 40);

        date.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        PanelSuperior.add(date);
        date.setBounds(670, 55, 190, 20);

        getContentPane().add(PanelSuperior);
        PanelSuperior.setBounds(0, 0, 800, 100);
    }// </editor-fold>//GEN-END:initComponents

    
    public void EdicionDeCodigoGenerado (){
        
        //AGREGAR ESCUCHA AL BOTON
        manejador = new Manejador();
        JBIniciosecc.addActionListener(manejador);
    }
    
    
    public class Manejador implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == JBIniciosecc){
                
                System.out.println("funciona");
                Login lg = new Login();
                lg.setVisible(true);
            }
            
        }
        
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoLogin;
    private javax.swing.JButton JBIniciosecc;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JPanel PanelImagenes;
    private javax.swing.JPanel PanelSuperior;
    private javax.swing.JLabel Texto1;
    private javax.swing.JLabel TituloDescanso;
    private javax.swing.JLabel TituloHotel;
    private javax.swing.JLabel barranegra;
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables




    // METODO QUE PERMITE EL FUNCIONAMIENTO DEL RELOJ EN EL LOGIN
    @Override
    public void run() {

        while (true) {
            try {
                Calendar c = Calendar.getInstance();
                hora = c.get(Calendar.HOUR_OF_DAY);
                if (hora > 12) {
                    hora = hora - 12;
                }

                minuto = c.get(Calendar.MINUTE);
                segundo = c.get(Calendar.SECOND);

                año = c.get(Calendar.YEAR);
                mes = c.get(Calendar.MONTH);
                dia = c.get(Calendar.DAY_OF_MONTH);
                SimpleDateFormat sdf = new SimpleDateFormat("hh:mm a");
                SimpleDateFormat df = new SimpleDateFormat("MM-dd-yyyy");
                Date dat = c.getTime();
                horastr = sdf.format(dat);
                añostr = df.format(dat);
                time.setText(horastr);
                date.setText(añostr);

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
}
