/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectodesarrollo;

import javax.swing.JOptionPane;

/**
 *
 * @author kevin
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(this);
        Placeholder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonIngresar = new javax.swing.JButton();
        UserPNG = new javax.swing.JLabel();
        Usuario = new javax.swing.JTextField();
        Contraseña = new javax.swing.JPasswordField();

        setTitle("Iniciar Sesión");
        setLocation(new java.awt.Point(0, 0));
        setName("login"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(38, 38, 38));
        jPanel1.setLayout(null);

        BotonIngresar.setBackground(new java.awt.Color(255, 189, 12));
        BotonIngresar.setText("Ingresar");
        BotonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonIngresar);
        BotonIngresar.setBounds(90, 220, 130, 32);

        UserPNG.setBackground(new java.awt.Color(255, 204, 51));
        UserPNG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/User.png"))); // NOI18N
        jPanel1.add(UserPNG);
        UserPNG.setBounds(-50, 30, 260, 260);

        Usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Usuario.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(Usuario);
        Usuario.setBounds(40, 150, 230, 30);

        Contraseña.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(Contraseña);
        Contraseña.setBounds(40, 180, 230, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 300, 300);
    }// </editor-fold>//GEN-END:initComponents

    public void Placeholder(){
        //Se asigna un placeholder a cada JTextfield
        TextPrompt campo = new TextPrompt(" Usuario", Usuario);
        TextPrompt campo2 = new TextPrompt(" Contraseña", Contraseña);
        
    }
    
    
    
    
    private void BotonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngresarActionPerformed
            
        
        
        if(Usuario.getText().equals("")){
            
            JOptionPane.showMessageDialog(null,"Por favor digite su usuario.");
            return;
            }
        else {
            if (Contraseña.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Por favor digite su contraseña.");
            return;
        }else{
                
                Bienvenida b = new Bienvenida();
                b.setVisible(false);
                this.setVisible(false);
                
                Gestión gs = new Gestión();
                gs.setVisible(true);
                
                System.out.println("funciona");
            }
       }
    }//GEN-LAST:event_BotonIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Login().setVisible(true);
              //  Login lg = new Login();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIngresar;
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JLabel UserPNG;
    private javax.swing.JTextField Usuario;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
